version: '3'
services:
  nginx:
    image: nginx:1.15
    volumes:
      - ./html:/usr/share/nginx/html/
      - ./conf:/etc/nginx/conf.d/
    ports:
      - "80:80"
    network_mode: bridge

  # redis:
  #   hostname: redis
  #   image: redis
  #   ports:
  #     - "6379:6379"
    
  # redis-commander:
  #  hostname: redis-commander
  #  image: rediscommander/redis-commander:latest
  #  environment:
  #  - REDIS_HOSTS=local:redis:6379
  #  ports:
  #  - 8001:8081
  
  mysql:
    image: mysql:5.7
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: xccloud
      MYSQL_USER: root
      MYSQL_PASSWORD: xccloud

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   ports:
  #     - "8000:80"
  #   depends_on:
  #     - mysql
  #   environment:
  #     PMA_HOST: mysql
  #     PMA_PORT: 3306
  #     PMA_USER: xccloud
  #     PMA_PASSWORD: xccloud
